/** @format */

import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import { BaseProviders } from '@/providers/BaseProvider';

import '@/styles/style.scss';
import { Overlay } from '@/ui/Overlay';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" data-bs-theme="light">
			<body
				id="app"
				className={`${inter.className} header-fixed header-tablet-and-mobile-fixed aside-fixed aside-secondary-enabled`}
				data-app-aside-minimize="on"
				data-app-drawer-aside="off"
				data-app-drawer="off"
			>
				<BaseProviders>
					<main className="d-flex flex-column flex-root">{children}</main>
				</BaseProviders>
				<div id="modal-root" />
				<Overlay />
			</body>
		</html>
	);
}
